spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false
    username: root
    password: 1470963

server:
  port: 80

#开启数据库字段的下划线命名和实体类属性驼峰命名的自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
